name: "push an image on merge to master"

on:
  push:
    branches:
      - master
jobs:
  build-and-push-amd64-k8s-rdma-shared-dev-plugin:
    name: image push amd64
    runs-on: ubuntu-22.04
    steps:
      - name: Set repository as lower-case output variable
        id: repo_name
        run: echo ::set-output name=repository::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

      - name: check out the repo
        uses: actions/checkout@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push k8s-rdma-shared-dev-plugin
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ steps.repo_name.outputs.repository }}:latest-amd64
          file: ./Dockerfile

  build-and-push-arm64-k8s-rdma-shared-dev-plugin:
    name: image push arm64
    runs-on: ubuntu-22.04
    steps:
      - name: Set repository as lower-case output variable
        id: repo_name
        run: echo ::set-output name=repository::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

      - name: check out the repo
        uses: actions/checkout@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push k8s-rdma-shared-dev-plugin
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/${{ steps.repo_name.outputs.repository }}:latest-arm64
          file: ./Dockerfile

  build-and-push-ppc64le-k8s-rdma-shared-dev-plugin:
    name: image push ppc64le
    runs-on: ubuntu-22.04
    steps:
      - name: Set repository as lower-case output variable
        id: repo_name
        run: echo ::set-output name=repository::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

      - name: check out the repo
        uses: actions/checkout@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push k8s-rdma-shared-dev-plugin
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/ppc64le
          tags: |
            ghcr.io/${{ steps.repo_name.outputs.repository }}:latest-ppc64le
          file: ./Dockerfile

  push-manifest:
    runs-on: ubuntu-22.04
    needs: [build-and-push-amd64-k8s-rdma-shared-dev-plugin,build-and-push-arm64-k8s-rdma-shared-dev-plugin,build-and-push-ppc64le-k8s-rdma-shared-dev-plugin]
    steps:
    - name: Set repository as lower-case output variable
      id: repo_name
      run: echo ::set-output name=repository::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create manifest for multi-arch images
      run: |
        docker buildx imagetools create -t ghcr.io/${{ steps.repo_name.outputs.repository }}:latest -t ghcr.io/${{ steps.repo_name.outputs.repository }}:sha-${{ github.sha }} \
        ghcr.io/${{ steps.repo_name.outputs.repository }}:latest-amd64 \
        ghcr.io/${{ steps.repo_name.outputs.repository }}:latest-arm64 \
        ghcr.io/${{ steps.repo_name.outputs.repository }}:latest-ppc64le
