name: go-static-analysis
on: [push, pull_request]
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: checkout PR
        uses: actions/checkout@v2
      - name: run make lint
        run: make lint
  hadolint:
    runs-on: ubuntu-22.04
    steps:
      - name: set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: checkout PR
        uses: actions/checkout@v2
      - name: run make hadolint
        run: make hadolint
